Fix unquoted boolean values
Boolean values need to be quoted or they won't be parsed as strings by the interpreter. It will throw these errors:

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.keycloak.environment.KC_HTTP_ENABLED contains false, which is an invalid type, it should be a string, number, or a null


ERROR: The Compose file './docker-compose.yml' is invalid because:
services.keycloak.environment.KC_HTTPS_ENABLED contains true, which is an invalid type, it should be a string, number, or a null


ERROR: The Compose file './docker-compose.yml' is invalid because:
services.keycloak.environment.KC_HOSTNAME_STRICT contains false, which is an invalid type, it should be a string, number, or a null